In [3]:
# check installation
import tensorflow as tf
tf.__version__

'1.12.0'

In [6]:
import numpy as np

In [7]:
a = np.array([1, 2, 3])
b = np.array([2, 4, 6])
c = np.add(a, b)

c

array([3, 6, 9])

In [14]:
# tensor - no immediate evaluation
x = tf.constant([1,2,3], name="x")
y = tf.constant([2,4,6], name="y")
z = tf.add(x,y) # no calculation happens at this line
print(z)

Tensor("Add_4:0", shape=(3,), dtype=int32)


In [15]:
# session.run
with tf.Session() as sess:
    result = sess.run(z) # a sess comes with a graph
    print(result) # calculation happens here!

[3 6 9]


In [16]:
# graph and session property of tf makes it lazy operator

In [17]:
# Variable

state = tf.Variable(0, name = 'counter') #a Variable init as 0, named as counter
current = tf.add(state, 1) # an operator:add 1 to the variable:state

update = tf.assign(state, current) #state <- current

#Note: Always remember to init operator if using Variable
init = tf.global_variables_initializer()
with tf.Session() as sess:
    sess.run(init)
    print(sess.run(state)) # print init value

    for _ in range(5):
        sess.run(update)
        print(sess.run(state))

0
1
2
3
4
5


In [18]:
# why tensorflow has this lazy propery is to let it runs faster
# maybe it's like the memory allocation i think

In [19]:
# Placeholder

p1 = tf.placeholder("float", None)
p2 = p1 * 2

print(p1)

with tf.Session() as sess:
    print(sess.run(p2, feed_dict={p1: [[1.1,2.2,3.3],[2,4,6]]}))

Tensor("Placeholder:0", dtype=float32)
[[ 2.2  4.4  6.6]
 [ 4.   8.  12. ]]


In [20]:
a, b, c, d = tf.constant(1), tf.constant(2), tf.constant(3),tf.constant(4)

add = tf.add(a,b)
mul = tf.multiply(add, c)
sub = tf.subtract(mul, d)

# TH: Try this
#add = a + b
#mul = add * c
#sub = mul - d

with tf.Session() as sess:
    fwrite = tf.summary.FileWriter('./lab1_tensorboard', sess.graph)
    print(sess.run(sub))
fwrite.close()

5
